### ISSUE TITLE
Are data sources closed?

### ISSUE THREAD

**Issue by pvlugter** [swaldman/c3p0-play#3]
There is a `deinitialize` method called `onStop` that doesn't seem to actually close anything:

https://github.com/swaldman/c3p0-play/blob/3b04e2cfe92f4517311931c445376ecd3bfb4a98/src/main/scala/com/mchange/sc/v2/c3p0/play/C3P0PlayDBPlugin.scala#L68

https://github.com/swaldman/c3p0-play/blob/3b04e2cfe92f4517311931c445376ecd3bfb4a98/src/main/scala/com/mchange/sc/v2/c3p0/play/C3P0PlayDBPlugin.scala#L154-L169

The `tryInitialize` method in `deinitialize` is not called on the data sources.

Compare this with the default BoneCP implementation in Play:

https://github.com/playframework/playframework/blob/2.3.6/framework/src/play-jdbc/src/main/scala/play/api/db/DB.scala#L254-L265

**Comment by swaldman** [comment]
Well, that was embarrassing.

Fixed as of c3p0-play-0.1.3.

Thank you very much for the detailed and helpful report.

**Comment by pvlugter** [comment]
Thanks!
